### ISSUE TITLE
Can't add my server

### ISSUE THREAD

**Issue by Klonger** [VeliovGroup/ostrio#4]
Hi, I get the error  `Bad response from host: Parse Error` when trying to add my server address (already tried with `http`, `https`, with `www` and without `www`)
<img width="725" alt="screen shot 2017-10-10 at 11 10 14" src="https://user-images.githubusercontent.com/9283366/31378668-56726584-adac-11e7-925b-944db5663876.png">

**Comment by dr-dimitru** [comment]
@Klonger thank you for submitting this issue.
The update will be delivered within an hour.

**Comment by dr-dimitru** [comment]
@Klonger thank you for contacting us.

Please support this project with:
 - Like at Facebook: https://www.facebook.com/ostrio.service
 - Follow on Twitter: https://twitter.com/ostrio_service
 - Star on GitHub: https://github.com/VeliovGroup/ostrio
 - Follow on Google Plus: https://plus.google.com/+OstrIo
