### ISSUE TITLE
How to Copy file collection data to another file collection, so the link()  in meteor is working

### ISSUE THREAD

**Issue by NageshAdhe** [VeliovGroup/ostrio#5]
Hi, I am using  ostrio file package, i want to maintain the history of my images which, are uploaded.
I just want to copy current data of file collection and insert to new file collection, In this when i inserted data to another collection,  we open the link by using link(), the uploaded image i not found in given link because the new id get generated. Please help me to get this resolve

**Comment by dr-dimitru** [comment]
Hello @NageshAdhe ,

Please reopen this issue at [`ostrio:files` repository](https://github.com/VeliovGroup/Meteor-Files).
