### ISSUE TITLE
I was reading Structured data basics and found errors when testing.

### ISSUE THREAD

**Issue by nikhilgoswami** [VeliovGroup/ostrio#6]
Here >>  ostrio/tutorials/website/social-networking/structured-data-basics.md
Error is in picture tag  
`<picture itemprop="logo" itemscope `itemtype="https://schema.org/ImageObject">`

The attribute logo.height has an invalid value.
The attribute logo.width has an invalid value.

**Comment by dr-dimitru** [comment]
Hey @nikhilgoswami ,

Thank you a lot for reporting about this. You're right, specs were updated.
Fixed in https://github.com/VeliovGroup/ostrio/commit/99e3696ad51eacf51ea45bf62f56d9067b490a99
