### ISSUE TITLE
Verification failed when redirection is done on frontend

### ISSUE THREAD

**Issue by patrickclercicube** [veliovgroup/ostrio#8]
Hello,

I try to add one of my server in ostr.io. I had the ostrio header in my nginx correctly set but the verification failed. 

My application receives first a response with the ostrio header in it, if not logged in the backed return a 401 response and the frontend redirect to the login page (with window.location modification), which is served by another server. 
My assumption is that ostr.io take the last page (redirection via frontend) to check the header instead of the first response. 

I have another site with a redirect managed by nginx with works correctly on ostr.io. 

It that a bug or do i need to change something in my application ? 

Thank you in advance. 

Best regards.

**Comment by dr-dimitru** [comment]
Hello @patrickclercicube ,

Yes, this is correct assumption.
Sound like if nginx would add header to all responses it would solve the problem. Try verification via DNS, file as alternative, or even `<meta />` tag if you find it convenient.

And let us know if you get some sort of error message?

**Comment by patrickclercicube** [comment]
Hello @dr-dimitru,

Thank you for your answer. I see your recommendation but the problem is a bit more complex and I wasn't explaining with sufficient details. 

I have 2 server which I monitor with ostr.io one for the login page, and another for the application page. 
So the login server has it's own ostrio header and token which is all OK. 
The web application has it's own ostrio header and nginx serve it correctly on the first response. But after window.location change the login page is displayed with it's ostrio header.  

The error I have is the next one

![image](https://user-images.githubusercontent.com/42430270/140321208-e8dd1aa8-1bd3-4ef3-8857-073485a47810.png)

Is it possible for you to check the first response header instead of the last one ? 
Or is it possible to share the ostrio token in header for multiple servers ? 

Thanks in advance for your help.

**Comment by dr-dimitru** [comment]
@patrickclercicube no, if it follows redirect, by all logical means we shouldn't read from first response data.
Disabling redirect temporary might help, but server might get removed later.

That's why we offer multiple verification methods, to match every case

**Comment by patrickclercicube** [comment]
Yes OK i see now. 

I have added a DNS TXT on my application, instead of nginx, and it works like a charm. 

Thanks you very much for your help.

**Comment by dr-dimitru** [comment]
Feel free to reopen it in case if the issue is still persists on your end.
